# Generated by Django 2.2.10 on 2020-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Digite o texto da alternativa.', max_length=20)),
                ('is_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alternative',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o título do questionário.', max_length=50)),
                ('password', models.CharField(help_text='Insira a senha do questionário.', max_length=20)),
            ],
            options={
                'verbose_name': 'Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Digite o texto da pergunta.', max_length=500)),
                ('questionnaire', models.ManyToManyField(to='questionnaire.Questionnaire')),
            ],
            options={
                'verbose_name': 'Quiz',
            },
        ),
    ]
