# Generated by Django 2.2.12 on 2020-04-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireConclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluded_at', models.DateTimeField(editable=False, verbose_name='Data de Conclusão da Lista')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Student')),
            ],
        ),
    ]
