# Generated by Django 2.2.11 on 2020-03-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternative',
            old_name='quiz',
            new_name='quiz_id',
        ),
    ]
