# Generated by Django 2.2.12 on 2020-04-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20200417_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Discipline', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.School', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='school_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.SchoolLevel', verbose_name='Nível Escolar'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Teacher', verbose_name='Professor'),
        ),
    ]
