# Generated by Django 2.2.12 on 2020-04-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20200418_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
