version: '3'

services:
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build: ./web
    
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      /bin/bash -c "
      sleep 7;
      python manage.py migrate;
      python util/populate.py;
      python manage.py runserver 0.0.0.0:8000"